---
- name: Install git
  chocolatey.chocolatey.win_chocolatey:
    name: git
    state: present

- name: Install Postman
  chocolatey.chocolatey.win_chocolatey:
    name: postman
    state: present

- name: Install Wireshark
  chocolatey.chocolatey.win_chocolatey:
    name: wireshark
    state: present

- name: Install HTTP Toolkit
  chocolatey.chocolatey.win_chocolatey:
    name: httptoolkit
    state: present

- name: Install Docker Desktop
  chocolatey.chocolatey.win_chocolatey:
    name: docker-desktop
    state: present
    ignore_checksums: true

- name: Include IDE installation tasks
  ansible.builtin.include_tasks: ides.yml
