---
- name: Bootstrap Chocolatey installation
  hosts: windows
  collections:
    - ansible.windows
  tasks:
      - name: Ensure Chocolatey installed from internal repo
        win_chocolatey:
          name: chocolatey
          state: present
          source: http://internal/odata/repo/ChocolateyInstall.ps1

      - name: Install git
        win_chocolatey:
          name: git
          state: present

      - name: Install vscode
        win_chocolatey:
          name: vscode
          state: present

      - name: Get the current user PATH
        win_environment:
          name: PATH
          level: user
        register: user_path
        ignore_errors: yes

      - name: Print path
        debug: msg='{{user_path}}'
